title: Hrithik Mhatre
logo: /img/GitHub.jpg
description: I am a final-year B.Tech student in Civil Engineering with a Minor in Computer Science and Engineering at IIT Bombay. My academic journey has allowed me to explore the intersection of civil engineering and data science, fostering a deep passion for applying technology to solve real-world challenges. I am driven by the potential of computational techniques and machine learning to create innovative solutions that can improve infrastructure, optimize systems, and address pressing global issues.
show_downloads: true
theme: jekyll-theme-minimal

