title: Hrithik Mhatre
logo: /img/GitHub.jpg
description: I’m a final-year Civil Engineering student with a Minor in Computer Science at IIT Bombay, passionate about using technology and data science to solve real-world problems.
show_downloads: true
theme: jekyll-theme-minimal

